config/routes.rb
Rails.application.routes.draw do
  root to: 'staticpage#home'

  resources :shops do
    resources :cars
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :shop

  validates_presence_of :make, :model, :year, :milage, :issues
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :cars

  validates_presence_of :name, :address, :hour, :base_rate, :descripton
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :shop
  before_action :car, except: [:index, :new, :create]

  def index
    @cars = @shop.cars
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = @shop.cars.new(car_params)
      if @car.save
        redirect_to shop_car_path(@shop, @car)
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to shop_car_path(@shop, @car)
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to shop_cars_path(@shop)
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :year, :milage, :issue)
  end

  def shop
    @shop = Shop.find(params[:shop_id])
  end

  def car
    @car = @shop.cars.find(params[:id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :shop, except: [:index, :new, :create]

  def index
    @shops = Shop.all
  end

  def show
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
      if @shop.save
        redirect_to shop_path(@shop)
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :address, :hour, :base_rate, :descripton) 
  end

   def shop
    @shop = Shop.find(params[:id])
   end
end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/views/cars/_form.html.erb
<%= form_for [@shop, @car] do |f| %>
<br />
  <%= f.label :make %>
  <%= f.text_field :make, required: true %>
<br />  
  <%= f.label :model %>
  <%= f.text_field :model, required: true %>
<br />
  <%= f.label :year %>
  <%= f.select :year, (1920..2016).to_a %>
<br />  
  <%= f.label :milage %>
  <%= f.text_field :milage %>
<br />
  <%= f.label :issues %>
  <%= f.text_area :issues, required: true %>
<br />
  <%= f.submit %>
<%= end %>

app/views/cars/edit.html.erb
<h3>Update Car</h3>


<%= render(partial: 'form')

app/views/cars/index.html.erb
<h1>Car#index</h1>
<p>Find me in app/views/car/index.html.erb</p>

app/views/cars/new.html.erb
<h3>Add Car</h3>

<%= render(partial: 'form')

app/views/cars/show.html.erb
<h1>Car#show</h1>
<p>Find me in app/views/car/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutoShops</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= link_to 'Home', root_path %> 
    <%= link_to 'All Shops', shops_path %>
    <%= yield %>
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_for @shop do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
<br />
  <%= f.label :address %>
  <%= f.text_field :address, required: true %>
<br />
  <%= f.label :hour %>
  <%= f.text_field :hour, required: true %>
<br />
  <%= f.label :base_rate %>
  <%= f.text_field :base_rate, required: true %>
<br />
  <%= f.label :descripton %>
  <%= f.text_area :descripton, required: true %>
<br />
  <%= f.submit %>

<% end %>

app/views/shops/edit.html.erb
<h2>Update Shop</h2>

<%= render(partial: 'form') %>

app/views/shops/index.html.erb
<h1>All Shops</h1>

<% if @shops.any? %>
  <ul>
    <% @shops.each do |shop| %>
      <li>
        <%= link_to shop.name, shop_path(shop) %>
      </li>
    <% end %>

  </ul>
<% else %>
  <p>There are currently no shops in the database. Please come back later.</p>
<% end %>

app/views/shops/new.html.erb
<h2>Enter Shop Info</h2>

<%= render(partial: 'form') %>

app/views/shops/show.html.erb
<h1>Shop</h1>

<h3> <%= @shop.name %> </h3>
<p>Address: <%= @shop.address %> </p>
<p>Hours of Operation: <%= @shop.hour %> </p>
<p>Base Rates(Some Restriction May Apply): <%= @shop.base_rate %></p>
<p>Description: <%= @shop.descripton %> </p>

<br />
<%= link_to 'Edit Shop', edit_shop_path(@shop) %>
<%= link_to 'Delete', shop_path(@shop), method: :delete, data: {confirm: "Are You Sure you would like to remove #{@shop.name}?"} %>
<%= link_to "#{@shop.name.pluralize} Cars Lot", shop_cars_path(@shop) %>

app/views/staticpage/about.html.erb
<h1>Staticpage#about</h1>
<p>Find me in app/views/staticpage/about.html.erb</p>

app/views/staticpage/home.html.erb
<h3>Hello Welcome</h3>

<p>This is the place to find an Auto Shop to fill all your automotive needs.</p>

<%= link_to 'Get Started', shops_path %>

<p>If you are a shop owner and would like to have your shop featured here Please follow the link below</p>

<%= link_to 'Add Shop', new_shop_path %>